# Generate and save state-US value added ratios
StateUS_VA_Ratio_2012 <- finalizeStateUSValueAddedRatio(2012)
usethis::use_data(StateUS_VA_Ratio_2012, overwrite = TRUE)
StateUS_VA_Ratio_2013 <- finalizeStateUSValueAddedRatio(2013)
usethis::use_data(StateUS_VA_Ratio_2013, overwrite = TRUE)
StateUS_VA_Ratio_2014 <- finalizeStateUSValueAddedRatio(2014)
usethis::use_data(StateUS_VA_Ratio_2014, overwrite = TRUE)
StateUS_VA_Ratio_2015 <- finalizeStateUSValueAddedRatio(2015)
usethis::use_data(StateUS_VA_Ratio_2015, overwrite = TRUE)
StateUS_VA_Ratio_2016 <- finalizeStateUSValueAddedRatio(2016)
usethis::use_data(StateUS_VA_Ratio_2016, overwrite = TRUE)
StateUS_VA_Ratio_2017 <- finalizeStateUSValueAddedRatio(2017)
usethis::use_data(StateUS_VA_Ratio_2017, overwrite = TRUE)

# Generate and save alternative state commodity output ratio
AlternativeStateCommodityOutputRatio_2012 <- getStateCommodityOutputRatioEstimates(2012)
usethis::use_data(AlternativeStateCommodityOutputRatio_2012, overwrite = TRUE)
AlternativeStateCommodityOutputRatio_2013 <- getStateCommodityOutputRatioEstimates(2013)
usethis::use_data(AlternativeStateCommodityOutputRatio_2013, overwrite = TRUE)
AlternativeStateCommodityOutputRatio_2014 <- getStateCommodityOutputRatioEstimates(2014)
usethis::use_data(AlternativeStateCommodityOutputRatio_2014, overwrite = TRUE)
AlternativeStateCommodityOutputRatio_2015 <- getStateCommodityOutputRatioEstimates(2015)
usethis::use_data(AlternativeStateCommodityOutputRatio_2015, overwrite = TRUE)
AlternativeStateCommodityOutputRatio_2016 <- getStateCommodityOutputRatioEstimates(2016)
usethis::use_data(AlternativeStateCommodityOutputRatio_2016, overwrite = TRUE)
AlternativeStateCommodityOutputRatio_2017 <- getStateCommodityOutputRatioEstimates(2017)
usethis::use_data(AlternativeStateCommodityOutputRatio_2017, overwrite = TRUE)
