# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: R CI/CD test #R-CMD-check

on:
  push:
    branches: [main, master]
    paths-ignore:
      - '**.md'  # prevent md files (e.g., README.md) in any repo dir from trigering workflow
      - '**.bib'
      - '**.ya?ml'  # captures both .yml and .yaml
      - '**.png'
      # - '**.Rmd'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
  pull_request:
    branches: [master, dev]
    paths-ignore:
      - '**.md'
      - '**.bib'
      - '**.ya?ml'
      - '**.png'
      # - '**.Rmd'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
  workflow_dispatch:  # also allow manual trigger, for testing purposes

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: R-CMD-check ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          #- {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      #GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} 
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            rcmdcheck
            devtools

      - uses: r-lib/actions/check-r-package@v2
      
      - name: Upload check results
        if: failure()  # if any of the previous steps fail, export a log
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check    
